development:
  adapter: postgresql
  database: salon21_dev
  min_messages: 'warning'
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: salon21_test
  min_messages: 'warning'
  pool: 5
  timeout: 5000
